export const insertStateCodes = `insert into public."StateCode"(state_code, state_name, country, region)
values('28', 'ANDHRA PRADESH','India','India Region'),
('29', 'KARNATAKA','India','India Region'),
('30', 'GOA','India','India Region'),
('31', 'LAKSHADWEEP','India','India Region'),
('32', 'KERALA','India','India Region'),
('33', 'TAMIL NADU','India','India Region'),
('34', 'PONDICHERRY','India','India Region'),
('35', 'ANDAMAN AND NICOBAR ISLANDS','India','India Region'),
('36', 'TELANGANA','India','India Region'),
('2', 'HIMACHAL PRADESH','India','India Region'),
('3', 'PUNJAB','India','India Region'),
('4', 'CHANDIGARH','India','India Region'),
('5', 'UTTARAKHAND','India','India Region'),
('6', 'HARYANA','India','India Region'),
('7', 'DELHI','India','India Region'),
('8', 'RAJASTHAN','India','India Region'),
('9', 'UTTAR PRADESH','India','India Region'),
('10', 'BIHAR','India','India Region'),
('11', 'SIKKIM','India','India Region'),
('12', 'ARUNACHAL PRADESH','India','India Region'),
('13', 'NAGALAND','India','India Region'),
('14', 'MANIPUR','India','India Region'),
('15', 'MIZORAM','India','India Region'),
('16', 'TRIPURA','India','India Region'),
('17', 'MEGHALAYA','India','India Region'),
('18', 'ASSAM','India','India Region'),
('19', 'WEST BENGAL','India','India Region'),
('20', 'JHARKHAND','India','India Region'),
('21', 'ODISHA','India','India Region'),
('22', 'CHHATTISGARH','India','India Region'),
('23', 'MADHYA PRADESH','India','India Region'),
('24', 'GUJARAT','India','India Region'),
('25', 'DAMAN AND DIU','India','India Region'),
('26', 'DADRA AND NAGAR HAVELI','India','India Region'),
('27', 'MAHARASHTRA','India','India Region'),
('1', 'JAMMU AND KASHMIR','India','India Region')`;
