export enum Category {
	CUSTOMER_CREATE = 1,
	CUSTOMER_UPDATE = 2,
	CUSTOMER_DELETE = 3,
	CUSTOMER_RESETMPIN = 4,
	CUSTOMER_BLOCK = 5,
	CUSTOMER_UNBLOCK = 6,
	CUSTOMER_RESETDEVICE = 7,
	CUSTOMER_CHANGEMOBILENUMBER = 8,
}
