export enum Operations {
	UPDATE = 'UPDATE',
	CREATE = 'CREATE',
	DELETE = 'DELETE',
	BLOCK = 'BLOCK',
	UNBLOCK = 'UNBLOCK',
	RESET_PIN = 'RESET_PIN',
	RESET_DEVICE = 'RESET_DEVICE',
	BLOCK_RL = 'BLOCK_RL',
	UNBLOCK_RL = 'UNBLOCK_RL',
}
